require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-comment")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.toggleterm")
require("core.plugin_config.autocompletion")
-- require("core.plugin_config.lsp-zero")
require("core.plugin_config.mason")
require("core.plugin_config.lspconfig")
